body:
  - id: bug-description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of what the bug is.
    type: textarea
    validations:
      required: true
  - id: desired-result
    attributes:
      label: Desired Result
      placeholder: Describe the desired result.
    type: textarea
    validations:
      required: true
  - id: logs
    attributes:
      description: Copy and paste any relevant log/stacktrace output.
      label: Relevant Logs
      render: Shell
    type: textarea
    validations:
      required: true
  - id: code
    attributes:
      description: |
        Provide your [Minimal, Complete, and
        Verifiable](https://stackoverflow.com/help/mcve) code example here, without the
        Reddit() initialization, so as to not leak private credentials.
      label: Code to reproduce the bug
      placeholder: "# Insert code here"
      render: Python
    type: textarea
    validations:
      required: true
  - id: credential-check
    attributes:
      label: |
        My code example does not include the `Reddit()` initialization to prevent
        credential leakage.
      options:
        - label: "Yes"
    type: checkboxes
    validations:
      required: true
  - id: previously-worked
    attributes:
      label: This code has previously worked as intended.
      multiple: false
      options:
        - "Not sure, I haven't used this code before."
        - "Yes"
        - "No"
    type: dropdown
    validations:
      required: true
  - id: environment
    attributes:
      description: What operating system, version, and environment are you working with.
      label: Operating System/Environment
      placeholder: "Example: macOS Monterey 12.0.0"
    type: input
    validations:
      required: true
  - id: python-version
    attributes:
      description: |
        What implementation and version of Python are you working with. CPython is
        assumed unless indicated otherwise.
      label: Python Version
      placeholder: 3.11.1
    type: input
    validations:
      required: true
  - id: praw-version
    attributes:
      label: PRAW Version
      placeholder: 'Example: 7.6.1'
    type: input
    validations:
      required: true
  - id: prawcore-version
    attributes:
      label: Prawcore Version
      placeholder: 2.3.0
    type: input
    validations:
      required: true
  - id: anything-else
    attributes:
      description: |
        Links or references? Anything that will give us more context about the issue
        you are encountering!
      label: Anything else?
    type: textarea
description: File a bug report
labels: ["bug", "unverified"]
name: Bug Report
