body:
  - id: bug-description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of what the bug is.
    type: textarea
    validations:
      required: true
  - id: desired-result
    attributes:
      label: Desired Result
      placeholder: Describe the desired result.
    type: textarea
    validations:
      required: true
  - id: logs
    attributes:
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      label: Relevant Logs
      render: Shell
    type: textarea
    validations:
      required: true
  - id: code
    attributes:
      description: |
        Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve)
        code example here, without the Reddit() initialization, to not leak private credentials.
        This will be automatically formatted into code, so no need for backticks.
      label: Code to reproduce the bug
      placeholder: "# Insert code here"
      render: Python
    type: textarea
    validations:
      required: true
  - id: credential-check
    attributes:
      label: My code example does not include the `Reddit()` initialization to prevent credential leakage.
      options:
        - label: "Yes"
          required: true
    type: checkboxes
  - id: previously-worked
    attributes:
      label: This code has previously worked as intended.
      multiple: false
      options:
        - "Not sure, I haven't used this code before."
        - "Yes"
        - "No"
    type: dropdown
    validations:
      required: true
  - id: environment
    attributes:
      description: What operating system, version, and environment are you working with.
      label: Operating System/Environment
      placeholder: "Example: macOS Monterey 12.0.0"
    type: input
    validations:
      required: true
  - id: python-version
    attributes:
      description: |
        What implementation and version of Python are you working with.
        CPython is assumed unless indicated otherwise.
      label: Python Version
      placeholder: "Example: 3.11.1"
    type: input
    validations:
      required: true
  - id: praw-version
    attributes:
      description: What version of PRAW. Obtain this by running `pip show praw`.
      label: PRAW Version
    type: input
    validations:
      required: true
  - id: prawcore-version
    attributes:
      description: What version of Prawcore. Obtain this by running `pip show prawcore`.
      label: Prawcore Version
    type: input
    validations:
      required: true
  - id: anything-else
    attributes:
      description: Links or references? Anything that will give us more context about the issue you are encountering!
      label: Anything else?
    type: textarea
description: File a bug report
labels: ["bug", "unverified"]
name: Bug Report
