jobs:
  ci:
    uses: SpazBots/glowing-octo-broccoli/.github/workflows/main-ci.yml@main
    with:
      repo: praw
      extra_test_dependencies: '&& echo $NETWORK_TEST_CLIENT_SECRET'
name: CI
on: [pull_request, push]
